### ISSUE TITLE
用qq音乐投放音频会报错

### ISSUE THREAD

**Issue by ab503044120** [dsafa22/AirplayServer#17]
本项目是不是只支持airplay2呢?
用qq音乐投放音频会有,解码会有问题
 aac_decode_frame error : 0x4002
似乎音频用得用alac解码

**Comment by FD-** [comment]
At the moment, only AirPlay mirroring is supported, not AirPlay audio or video. AirPlay mirroring uses the AAC audio codec, while AirPlay audio uses ALAC. For adding AirPlay audio support, the [ShairPlay](https://github.com/juhovh/shairplay) project is a good reference (not least because AirplayServer was derived from it).

**Comment by dsafa22** [comment]
项目以视频为主，单独投放音频没有做适配，所以也没有加入alac的解码。
